name: "Deploy Certificate"

on:
  push:
    branches: [main]
    paths:
      - "cert/**"
  pull_request:
    branches: [main]
    paths:
      - "cert/**"
  workflow_dispatch:

jobs:
  call-terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working-directory: cert
    secrets: inherit
