name: "Deploy stage"

on:
  push:
    branches: [main]
    paths:
      - "stage/service/**"
  pull_request:
    branches: [main]
    paths:
      - "stage/service/**"
  workflow_dispatch:
    inputs:
      command:
        description: "Terraform command to run"
        type: choice
        options:
          - plan
          - apply

jobs:
  run-terraform:
    uses: ./.github/workflows/run_terraform.yml
    with:
      working-directory: stage/service
      command: ${{ github.event.inputs.command }}
    secrets: inherit
