name: "Deploy stage"

on:
  push:
    branches: [main]
    paths:
      - "service/stage/**"
  pull_request:
    branches: [main]
    paths:
      - "service/stage/**"
  workflow_dispatch:

jobs:
  run-terraform:
    uses: ./.github/workflows/run_terraform.yml
    with:
      working-directory: service/stage
    secrets: inherit
