name: "Deploy prod"

on:
  push:
    branches: [main]
    paths:
      - "service/prod/**"
  pull_request:
    branches: [main]
    paths:
      - "service/prod/**"
  workflow_dispatch:

jobs:
  run-terraform:
    uses: ./.github/workflows/run_terraform.yml
    with:
      working-directory: service/prod
    secrets: inherit
